config/routes.rb
Rails.application.routes.draw do

  root to: "users#index"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy", as: "logout"
  get '/timeline', to: "users#timeline"
  get '/mentions', to: "users#mentions"
  get 'followerslist', to: "users#followerslist"

  resources :hashtags, only: [:show]
  resources :statuses, only: [:new, :create]
  resources :users, only: [:new, :create] do
    member do
      post 'follow'
      post 'unfollow'
    end
  end
  get '/:username', to: "users#show", as: "user"
end

app/models/mention.rb
class Mention < ActiveRecord::Base
  belongs_to :user
  belongs_to :status

  def mark_viewed!
    self.update(viewed_at: DateTime.now)
  end
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :leader, class_name: 'User', foreign_key: 'leader_id'
  belongs_to :follower, class_name: 'User' ,foreign_key: 'follower_id'
end

app/models/status.rb
class Status < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: "user_id"
  validates :creator, presence: true
  validates :body, presence: true, length: { minimum: 5 }

  after_save :extract_mentions



  def extract_mentions
    mentions = self.body.scan(/@(\w*)/).flatten
    mentions.each do |mention|
      user = User.find_by username: mention
      if user
        Mention.create(user_id: user.id, status_id: self.id)
      end
    end    
  end

  def self.get_status_of_hashtag(hashtag)
    where("body LIKE '%##{hashtag}%'")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :statuses
  has_many :mentions

  has_many :following_relationships, class_name: 'Relationship', foreign_key: 'follower_id'
  has_many :follower_relationships , class_name: 'Relationship', foreign_key: 'leader_id'

  has_many :following_users, through: 'following_relationships', source: 'leader'
  has_many :follower_users, through: 'follower_relationships', source: 'follower'

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true

  def unread_mention_amount
    self.mentions.where(viewed_at: nil).size
  end

  def mark_mentions_viewed!
    self.mentions.each do |mention|
      mention.mark_viewed!
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :unread_mention_amount_for_current_user, :generate_links

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You haven't logged in!!"
      redirect_to root_path
    end
  end

  def wrong_path
    flash[:error] = "Something goes wrong!!"
    redirect_to :root
  end

  def unread_mention_amount_for_current_user
    current_user.unread_mention_amount
  end

  def generate_links(status_body)
    status_body = generate_hashtag_links(status_body)
    generate_mentions_links(status_body)
  end

  def generate_hashtag_links(status_body)
    status_body.gsub(/#(\w+)/, "<a href=/hashtags/\\1>#\\1</a>").html_safe
  end

  def generate_mentions_links(status_body)
    status_body.gsub(/@(\w+)/, "<a href=/\\1>@\\1</a>").html_safe
  end

  def extract_statuses_from_mentions
    statuses = []
    current_user.mentions.each do |mention|
      statuses << mention.status
    end
    statuses
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @statuses = Status.get_status_of_hashtag(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #login form
  end

  def create
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "You've logged in successfully!"
      redirect_to timeline_path 
      #login success
    else
      flash.now[:error] = "Something goes wrong with your usename or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You have logged out!!'
    redirect_to login_path
  end
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)
    user = current_user
    @status.creator = user
    if @status.save
      flash[:notice] = "Successfully Create a Status!!"
      redirect_to user_path(user.username)
    else 
      render :new
    end
        
  end



  private

  def status_params
    params.require(:status).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:follow, :unfollow, :timeline]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:notice] = "Register Successfully!!"
      redirect_to user_path(@user.username)
    else
      render :new
    end
  end

  def show
    @user = User.find_by(username: params[:username])
  end

  def follow
    leader = User.find(params[:id])
    if leader
      current_user.following_users << leader
      flash[:notice] = "You have followed #{leader.username}!!"
      redirect_to user_path(leader.username)
    else
      wrong_path
    end
  end

  def unfollow
    user = User.find(params[:id])
    if user
      relationship = current_user.following_relationships.find_by(follower_id: current_user.id, leader_id: user.id)
      relationship.destroy
      flash[:notice] ="You are no longer follow #{user.username}"
      redirect_to :root
    else
      wrong_path
    end
  end

  def timeline
    @statuses = [ ]
    current_user.following_users.each do |user|
      @statuses << user.statuses
    end
    @statuses.flatten!   ##todo : sort by created time
  end

  def mentions
    current_user.mark_mentions_viewed!
    @statuses = extract_statuses_from_mentions
  end

  def followerslist
      @followers = []
      current_user.follower_users.each do |follower|
          @followers << follower
      end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hashtags/show.html.erb
<%= render 'shared/header', header: "All the Status with ##{params[:id]}" %>
<%= render 'shared/status', statuses: @statuses %>

app/views/layouts/_flash_messages.html.erb
  <% if flash.keys.any? %>
    <% flash.keys.each do |key| %>
      <div class="alert alert-<%= key == 'notice' ? "success" : "danger" %>" role="alert">
      <%= flash[key] %>
      </div>
    <% end %>
  <% end %>  

app/views/layouts/_top_nav.html.erb
<ul class="nav nav-pills">
  <li role="presentation"> <%= link_to 'Home', root_path %></li>
  <% if logged_in? %>
    <li role="presentation"><%= link_to "logout", logout_path %></li>
    <li role="presentation"><%= link_to "New Status", new_status_path %></li>
    <li role="presentation"><%= link_to "Timeline", timeline_path %></li>
    <li role="presentation">
      <%= link_to "Mentions(#{unread_mention_amount_for_current_user})", mentions_path %>
    </li>   
  <% else %>
    <li role="presentation"><%= link_to "Register", new_user_path %></li>
    <li role="presentation"><%= link_to "login", login_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "container">
    <%= render 'layouts/top_nav' %>
    <%= render 'layouts/flash_messages' %>
    <%= yield %>    
  </div>


</body>
</html>

app/views/shared/_errors.html.erb
<!-- This is a generic partial that display all the errors of ActiveRecord Object -->
<% if obj.errors.any? %>
  <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_header.html.erb
<h3><%= header %></h3>
<hr>

app/views/shared/_status.html.erb
<div class="row">
  <div class="col-sm-6">
    <% statuses.each do |status| %>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <%= status.creator.username %>
        </div>
        <div class="panel-body">
          <%= generate_links(status.body) %>
        </div>
        <div class="panel-footer">
          by <%= status.creator.username %> at <%= status.created_at %>
        </div>
      </div>
    <% end %>  
  </div>  
</div>

app/views/statuses/new.html.erb
<%= render 'shared/errors', obj: @status %>
<%= render 'shared/header', header: 'Create a New Status' %>
<% if logged_in? %>
  <div class="col-sm-6">
    <%= form_for @status do |f| %>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <%= f.submit "Create Status" ,class: "btn btn-success"%>
    <% end %>
  </div>
<% end %>

app/views/users/index.html.erb
<% if logged_in? %>
  <h1><%= "Welcome #{current_user.username}" %></h1>
<% end %>
<%= render 'shared/header', header: 'All users' %>
<ul>
  <% @users.each do |user| %>
    <li><%= link_to user.username, user_path(user.username) %></li>
  <% end %>
</ul>

app/views/users/mentions.html.erb
<%= render 'shared/header', header: 'Mentions' %>
<%= render 'shared/status', statuses: @statuses %>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>
<%= render 'shared/header', header: 'Regiser' %>
<div class="col-sm-4">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>      
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>     
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <%= f.submit "Register", class: "btn btn-info" %>
  <% end %>

</div>

app/views/users/show.html.erb
<h3><%= link_to "@#{@user.username}", user_path(@user.username) %></h3>
<div class="follow_unfollow_button">
  <% if logged_in? && (current_user != @user) %>
    <% if !current_user.following_users.include?(@user) %>
      <%= link_to '+ Follow', follow_user_path(@user), method: 'post', class: "btn btn-success" %>
    <% else %>
      <%= link_to '-unfollow', unfollow_user_path(@user), method: 'post', class: "btn btn-warning" %>    
    <% end %>
  <% end %> 
</div>


<%= render 'shared/status', statuses: @user.statuses %>

app/views/users/timeline.html.erb
<%= render 'shared/header', header: 'Timeline' %>
<%= render 'shared/status', statuses: @statuses %>